name: fendhaaroo
description: Task Tracker

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^9.3.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  uuid: ^4.5.0
  intl: ^0.19.0
  path_provider: ^2.0.11
  csv: ^6.0.0
  animate_do: ^3.3.4
  flutter_beautiful_popup: ^1.7.0
  panara_dialogs: ^0.1.2
  lottie: ^3.1.2
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  hive_generator: ^2.0.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/lottie/
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
